//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Global"",
            ""id"": ""89c4807e-3996-4ba7-92e5-caf62b57354e"",
            ""actions"": [
                {
                    ""name"": ""SwitchTestInputs"",
                    ""type"": ""Button"",
                    ""id"": ""75c15c3d-906f-41cb-9adf-91ed95a664ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3bb94d8-06cf-4252-96cb-e6ba8075e6d8"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchTestInputs"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Tests"",
            ""id"": ""7c4536ac-cc5a-43b9-8290-c1bdf358769c"",
            ""actions"": [
                {
                    ""name"": ""TestMe"",
                    ""type"": ""Button"",
                    ""id"": ""3ce09ee9-1a44-41c2-919a-39db06821cf2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""76a32432-9037-4b40-8139-bf433a792219"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestMe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Donut"",
            ""id"": ""cf985a57-c77c-4b5d-a56e-6f04df405c80"",
            ""actions"": [
                {
                    ""name"": ""Thrust"",
                    ""type"": ""Button"",
                    ""id"": ""3c7f700d-efd4-4640-a36b-17fda1cb47a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Breake"",
                    ""type"": ""Button"",
                    ""id"": ""290750fe-91e9-4dc9-b75a-d3750a80d37c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b1dc5e08-99c6-4234-9a3c-18f4bfbf3608"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""22bda10f-b7cc-42c0-b459-7d6ed2125915"",
                    ""path"": ""1DAxis(minValue=0)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""99b8ad29-f21b-4429-b945-e6f135f00653"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b4cad66b-3116-473f-bbdf-4644d5a5e332"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Breake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70cecc4a-a95c-4dc9-94be-a78307b43afa"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InGameGeneral"",
            ""id"": ""6f3d2446-ad73-4cfb-a54d-c887e2a51c59"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""7a37925d-a80a-4713-9a66-18bd812e97db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1f8e8e02-8873-4bcd-aa81-83c72d29da34"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Global
        m_Global = asset.FindActionMap("Global", throwIfNotFound: true);
        m_Global_SwitchTestInputs = m_Global.FindAction("SwitchTestInputs", throwIfNotFound: true);
        // Tests
        m_Tests = asset.FindActionMap("Tests", throwIfNotFound: true);
        m_Tests_TestMe = m_Tests.FindAction("TestMe", throwIfNotFound: true);
        // Donut
        m_Donut = asset.FindActionMap("Donut", throwIfNotFound: true);
        m_Donut_Thrust = m_Donut.FindAction("Thrust", throwIfNotFound: true);
        m_Donut_Breake = m_Donut.FindAction("Breake", throwIfNotFound: true);
        m_Donut_Jump = m_Donut.FindAction("Jump", throwIfNotFound: true);
        // InGameGeneral
        m_InGameGeneral = asset.FindActionMap("InGameGeneral", throwIfNotFound: true);
        m_InGameGeneral_Pause = m_InGameGeneral.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Global
    private readonly InputActionMap m_Global;
    private IGlobalActions m_GlobalActionsCallbackInterface;
    private readonly InputAction m_Global_SwitchTestInputs;
    public struct GlobalActions
    {
        private @PlayerInput m_Wrapper;
        public GlobalActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchTestInputs => m_Wrapper.m_Global_SwitchTestInputs;
        public InputActionMap Get() { return m_Wrapper.m_Global; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GlobalActions set) { return set.Get(); }
        public void SetCallbacks(IGlobalActions instance)
        {
            if (m_Wrapper.m_GlobalActionsCallbackInterface != null)
            {
                @SwitchTestInputs.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnSwitchTestInputs;
                @SwitchTestInputs.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnSwitchTestInputs;
                @SwitchTestInputs.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnSwitchTestInputs;
            }
            m_Wrapper.m_GlobalActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SwitchTestInputs.started += instance.OnSwitchTestInputs;
                @SwitchTestInputs.performed += instance.OnSwitchTestInputs;
                @SwitchTestInputs.canceled += instance.OnSwitchTestInputs;
            }
        }
    }
    public GlobalActions @Global => new GlobalActions(this);

    // Tests
    private readonly InputActionMap m_Tests;
    private ITestsActions m_TestsActionsCallbackInterface;
    private readonly InputAction m_Tests_TestMe;
    public struct TestsActions
    {
        private @PlayerInput m_Wrapper;
        public TestsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @TestMe => m_Wrapper.m_Tests_TestMe;
        public InputActionMap Get() { return m_Wrapper.m_Tests; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TestsActions set) { return set.Get(); }
        public void SetCallbacks(ITestsActions instance)
        {
            if (m_Wrapper.m_TestsActionsCallbackInterface != null)
            {
                @TestMe.started -= m_Wrapper.m_TestsActionsCallbackInterface.OnTestMe;
                @TestMe.performed -= m_Wrapper.m_TestsActionsCallbackInterface.OnTestMe;
                @TestMe.canceled -= m_Wrapper.m_TestsActionsCallbackInterface.OnTestMe;
            }
            m_Wrapper.m_TestsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TestMe.started += instance.OnTestMe;
                @TestMe.performed += instance.OnTestMe;
                @TestMe.canceled += instance.OnTestMe;
            }
        }
    }
    public TestsActions @Tests => new TestsActions(this);

    // Donut
    private readonly InputActionMap m_Donut;
    private IDonutActions m_DonutActionsCallbackInterface;
    private readonly InputAction m_Donut_Thrust;
    private readonly InputAction m_Donut_Breake;
    private readonly InputAction m_Donut_Jump;
    public struct DonutActions
    {
        private @PlayerInput m_Wrapper;
        public DonutActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Thrust => m_Wrapper.m_Donut_Thrust;
        public InputAction @Breake => m_Wrapper.m_Donut_Breake;
        public InputAction @Jump => m_Wrapper.m_Donut_Jump;
        public InputActionMap Get() { return m_Wrapper.m_Donut; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DonutActions set) { return set.Get(); }
        public void SetCallbacks(IDonutActions instance)
        {
            if (m_Wrapper.m_DonutActionsCallbackInterface != null)
            {
                @Thrust.started -= m_Wrapper.m_DonutActionsCallbackInterface.OnThrust;
                @Thrust.performed -= m_Wrapper.m_DonutActionsCallbackInterface.OnThrust;
                @Thrust.canceled -= m_Wrapper.m_DonutActionsCallbackInterface.OnThrust;
                @Breake.started -= m_Wrapper.m_DonutActionsCallbackInterface.OnBreake;
                @Breake.performed -= m_Wrapper.m_DonutActionsCallbackInterface.OnBreake;
                @Breake.canceled -= m_Wrapper.m_DonutActionsCallbackInterface.OnBreake;
                @Jump.started -= m_Wrapper.m_DonutActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_DonutActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_DonutActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_DonutActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Thrust.started += instance.OnThrust;
                @Thrust.performed += instance.OnThrust;
                @Thrust.canceled += instance.OnThrust;
                @Breake.started += instance.OnBreake;
                @Breake.performed += instance.OnBreake;
                @Breake.canceled += instance.OnBreake;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public DonutActions @Donut => new DonutActions(this);

    // InGameGeneral
    private readonly InputActionMap m_InGameGeneral;
    private IInGameGeneralActions m_InGameGeneralActionsCallbackInterface;
    private readonly InputAction m_InGameGeneral_Pause;
    public struct InGameGeneralActions
    {
        private @PlayerInput m_Wrapper;
        public InGameGeneralActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_InGameGeneral_Pause;
        public InputActionMap Get() { return m_Wrapper.m_InGameGeneral; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameGeneralActions set) { return set.Get(); }
        public void SetCallbacks(IInGameGeneralActions instance)
        {
            if (m_Wrapper.m_InGameGeneralActionsCallbackInterface != null)
            {
                @Pause.started -= m_Wrapper.m_InGameGeneralActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_InGameGeneralActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_InGameGeneralActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_InGameGeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public InGameGeneralActions @InGameGeneral => new InGameGeneralActions(this);
    public interface IGlobalActions
    {
        void OnSwitchTestInputs(InputAction.CallbackContext context);
    }
    public interface ITestsActions
    {
        void OnTestMe(InputAction.CallbackContext context);
    }
    public interface IDonutActions
    {
        void OnThrust(InputAction.CallbackContext context);
        void OnBreake(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
    public interface IInGameGeneralActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
